name: Push Latest Image

on:
  pull_request:
    types: [closed] 
jobs:
  build:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Authenticate into Google Cloud Platform
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Configure Docker to use Google Cloud Platform
      uses: actions/gcloud/cli@master
      with:
        args: "auth configure-docker --quiet"
    - name: Pull Latest Image
      uses: actions/gcloud/cli@master
      with:
        entrypoint: sh
        args: -c "docker pull gcr.io/replicated-test/rasa-demo:latest || true"
    - name: Set Build ID from PR Ref
      run: echo ::set-env name=BUILD_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    - name: Build Image
      run: |
        docker build -t gcr.io/replicated-test/rasa-demo:pr$BUILD_NUMBER -t gcr.io/replicated-test/rasa-demo:testgithub --cache-from gcr.io/replicated-test/rasa-demo:latest .
    - name: Push PR Image to Google Cloud Container Registry
      uses: actions/gcloud/cli@master
      if: github.event.pull_request.merged == false
      with:
        entrypoint: sh
        args: -c "docker push gcr.io/replicated-test/rasa-demo:testgithub"