name: Push Latest Image

on:
  pull_request:
    types: [closed] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull request merged
      if: github.event.pull_request.merged == false
      run: echo merged